# Generated by Django 5.2.3 on 2025-06-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
