# Generated by Django 5.2.3 on 2025-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes_app', '0003_usuarios_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
