# Generated by Django 5.2.3 on 2025-06-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes_app', '0004_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
